version: '2'

services:
    madc:
        image: madc
        container_name: madc
        volumes:
            - /home/bcrlab/malachy7/madc_docker/config/flask/:/config
            - /home/bcrlab/malachy7/madc_docker/studies/:/studies
        restart: unless-stopped
        environment:
            - GUNICORN_WORKERS=1
            - CELERY_WORKERS=1
        ulimits:
            nofile:
                soft: "65536"
                hard: "65536"
networks:
    default:
        external: true
        name: digby_network
