version: '2'

services:
    madc:
        image: madc
        container_name: madc
        volumes:
            - /home/ubuntu/clareo_docker/config/flask:/config
            - /home/bcrlab/malachy7/minimal_adc/containers/madc/app:/app
            - /home/bcrlab/malachy7/minimal_adc/containers/madc/log:/log
            - /home/bcrlab/malachy7/minimal_adc/containers/madc/studies:/studies
            - /misc/work/sequence_data_store/:/misc/work/sequence_data_store/
        restart: unless-stopped
        environment:
            - GUNICORN_WORKERS=1
            - CELERY_WORKERS=1
        ulimits:
            nofile:
                soft: "65536"
                hard: "65536"
networks:
    default:
        external: true
        name: digby_network
